### ISSUE TITLE
How to get a BimServerClientFactory in bimserver-client-lib-1.4.0-RC-2015-03-14?

### ISSUE THREAD

**Issue by Syvon** [opensourceBIM/BIMserver#206]
Hello,
I'm new to bimserver-client-lib-1.4.0-RC-2015-03-14.Now I want to get a BimServerClientFactory in following way which works in bimserver-client-lib-2013-09-09.00-02-31.

    BimServerClientFactory factory = new JsonBimServerClientFactory("http://localhost:8082");
It can't work.The Eclipse say "JsonBimServerClientFactory(MetaDataManager,String)".
What should I do?
Many thanks in advance.

**Comment by rubendel** [comment]
In BIMserver 1.4 there is a new way of creating the ClientFactories. I'll document on the wiki soon. 
```
LocalDevSetup.setupJson(address);
```

**Comment by Syvon** [comment]
Thank you very much.
Can you give more examples on the wiki?
We would appreciate it.

**Comment by Syvon** [comment]
I tried it,the eclipse complains as follows:

    Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
	at org.bimserver.client.AbstractBimServerClientFactory.<init>(AbstractBimServerClientFactory.java:64)
	at org.bimserver.client.json.JsonBimServerClientFactory.<init>(JsonBimServerClientFactory.java:44)
	at org.bimserver.LocalDevSetup.setupJson(LocalDevSetup.java:87)
	at com.example.wang.BIMserver0504.main(BIMserver0504.java:34)
    Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

**Comment by rubendel** [comment]
Ah a few libraries were missing in the build, newest RC release should work.
